### ISSUE TITLE
Upgrade MonogDB from 3.6.3 to 3.6.23

### ISSUE THREAD

**Issue by Dazog** [mbentley/docker-omada-controller#108]
Update MongoDB to protect against the many cve's

Upgrade MonogDB from 3.6.3 to 3.6.23

Thank you

**Comment by mbentley** [comment]
Assuming you're talking about the `amd64` variant, this is not possible nor is it necessary.  It is packaged by upstream as we are installing the `mongodb-server-core` package from Ubuntu 18.04.

There are not "many CVEs" in MongoDB packaged by Canonical as they backport fixes.  If you have data that says otherwise, I would be happy to review it.  See the scan results from Trivy:

<img width="1383" alt="screenshot 2021-05-26 at 12 48 46 PM" src="https://user-images.githubusercontent.com/414445/119700107-d82d2400-be20-11eb-8cca-42d9b84d490f.png">
