### ISSUE TITLE
Change user/group of container

### ISSUE THREAD

**Issue by laheym** [mbentley/docker-omada-controller#212]
**Is your feature request related to a problem? Please describe.**
Change the user/group (defined with environment variables) of the container after startup.  This will allow administrators to set appropriate permissions on the persistent volumes

**Describe the solution you'd like**
Add two environment variables to the container (e.g. linuxserver.io containers typically use PUID and PGID) that define the user and group that the will container runs as.

**Comment by mbentley** [comment]
Shouldn't be a problem to implement - I'm already using `gosu` to change to the `omada` user; would just need to move the creation of the `omada` user from the install.sh script to the entrypoint script to execute as a part of the entrypoint; likely the very beginning.

I'll probably only backport it to the 4.x and 5.x versions; maybe also 3.2.x just because it is last of the older version that supports some older versions of hardware.

**Comment by laheym** [comment]
Thanks Matt.  And thanks for creating the container - it made entry into the omada ecosystem much easier.
