### ISSUE TITLE
[Bug]: Potential thread leak

### ISSUE THREAD

**Issue by xinbinhuang** [mbentley/docker-omada-controller#272]
### Controller Version

v5.7.4

### Describe the Bug

Observer a potential thread leak, not sure what is the exact cause yet. Will monitor for a few days and try to reproduce it, then report back. Not sure if this is a bug on the image or on omada itself 🤷 

Memory & thread change in the last 7 days, there is a sudden jump from 800Mb -> 1.3Gb. Threads are slowly climbing up.
<img width="1582" alt="Screen Shot 2022-12-11 at 11 13 37 PM" src="https://user-images.githubusercontent.com/27927454/206983191-65a66481-6912-4fee-b777-f0977a0f5028.png">

Manually kill & restart the pod, then the memory drop back to ~800 Mb
<img width="1606" alt="Screen Shot 2022-12-11 at 11 14 19 PM" src="https://user-images.githubusercontent.com/27927454/206983290-de0e7f5c-f7c0-4b15-8689-b37e022f9540.png">

### Expected Behavior

na

### Steps to Reproduce

na

### How You're Launching the Container

```plain
k8s
```

### Container Logs

```plain
na
```

**Comment by mbentley** [comment]
I'd be curious if there is anything in the logs that might give an idea as to if it was executing a process when the memory jump happened.  I'm also interested in your usage of the controller - what sort & how many devices are connected to your controller?

I only have three EAP245 APs but I haven't seen overly excessive memory jumps on my container; I've been running 5.7.4 since it's been released.  I have a 4GB memory limit set on the container; currently sitting at 1.193GiB used at the moment:

<img width="1595" alt="screenshot 2022-12-12 at 6 55 53 AM" src="https://user-images.githubusercontent.com/414445/207039207-c11dd444-196e-4900-97f4-5af51b25dd4e.png">

Will have to check but I don't think I'm currently pulling # of threads or even processes through the Docker Telegraf plugin but I'm currently seeing 305 PIDs in the container from `docker stats` for a quick check.

**Comment by Stupco** [comment]
I've just seen something similar, this memory leak doesn't happen when the Omada Container isn't running:
![image](https://user-images.githubusercontent.com/64451616/212888160-7ac5323a-1e3c-4568-90ee-575f2140ba04.png)
Controller Version: 5.7.4

**Comment by mbentley** [comment]
I just double checked the java process arguments to make sure there isn't something new that I missed but I don't see anything; only things really different here is passing `-Xms128m -Xmx1024m` and omitting `/usr/share/java/commons-daemon.jar` from the classpath which I am pretty certain is only needed with jsvc.

from the Dockerfile CMD:
```
/usr/bin/java -server -Xms128m -Xmx1024m -XX:MaxHeapFreeRatio=60 -XX:MinHeapFreeRatio=30 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/tplink/EAPController/logs/java_heapdump.hprof -Djava.awt.headless=true -cp /opt/tplink/EAPController/lib/*::/opt/tplink/EAPController/properties: com.tplink.smb.omada.starter.OmadaLinuxMain
```

from the `control.sh` typically used on a native install:
```
-server -XX:MaxHeapFreeRatio=60 -XX:MinHeapFreeRatio=30 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/tplink/EAPController/logs/java_heapdump.hprof -Djava.awt.headless=true -cp /usr/share/java/commons-daemon.jar:/opt/tplink/EAPController/lib/*:/opt/tplink/EAPController/properties com.tplink.smb.omada.starter.OmadaLinuxMain
```

Since there is another data point, anything in the logs indicating that a process is running in particular when you see jumps in memory usage?  When it comes to things like memory leaks, those are probably things that would have to be addressed to [TP-Link through their forums](https://community.tp-link.com/en/business/forum/582) since they have the ability to fix things in the software itself.
