### ISSUE TITLE
[Upgrade]: 5.8.4 released

### ISSUE THREAD

**Issue by evolucja** [mbentley/docker-omada-controller#275]
Hi, it looks like there is a version 5.8.4 for Windows released. How long does it usually take to release also the Linux version so the Docker image could be updated as well?

Thanks
Dave

**Comment by mbentley** [comment]
It's whenever they (TP-Link) releases it - seems pretty random though.  As soon as they release a new version though, I am usually able to update the Docker image pretty quickly - sometimes in a few hours but I definitely aim to have it done within 24 hours unless there are major changes.  Usually the runtime environment changes are minimal so it's a quick process.

**Comment by evolucja** [comment]
Thank you. I was just curious how long it usually takes as I've been recently onboarded to the Omada ecosystem :)

**Comment by mbentley** [comment]
No problem - I've seen them release a Windows release one month, Linux the next - there is no rhyme or reason for when and how they release.  Seems independent from each other.  Sometimes the Linux release comes out first, other times the Windows.  One consistent thing is that the hardware controller from TP-Link seems to lag behind much further than either the Linux or Windows software controllers.

**Comment by guitarmanusa** [comment]
On the latest-chromium (5.7.4) when logging into the controller I get a pop message on the dashboard saying a "newer" version is available: v5.7.4 Build 202211051_1668995905916, if I'm reading the build date of this version correctly, 05 Nov 2022, would you say this is actually older than the build date of 5.7.4 posted on TP Link's site? (11/21/2022)

**Comment by mbentley** [comment]
Not sure why that would be exactly - I just started a new controller from the `latest-chromium` tag and it's reporting as being version 5.7.4 and that it is up to date:

<img width="997" alt="screenshot 2023-01-14 at 1 12 28 PM" src="https://user-images.githubusercontent.com/414445/212488781-4755a8df-17f9-426f-bda7-7335a2b97a42.png">

As far as I know, there have not been any updates to the package since 5.7.4 was released - it's been on `https://static.tp-link.com/upload/software/2022/202211/20221121/Omada_SDN_Controller_v5.7.4_Linux_x64.tar.gz` [since I merged support for 5.7.4](https://github.com/mbentley/docker-omada-controller/commit/ef38cd36591b6d918b1518f3528d24d3f8e45368#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR45) and the tarball available from the TP-Link site is still reporting as the same.

**Comment by guitarmanusa** [comment]
Of course after I post this the message goes away :( I swear I'm not crazy!  But I'm glad I'm now also showing the same!  Thanks!

**Comment by bartoszkaminski** [comment]
Linux version is ready 🙂
