### ISSUE TITLE
[Feature]: Publish latest Beta 5.13.10

### ISSUE THREAD

**Issue by Gruni22** [mbentley/docker-omada-controller#358]
### What problem are you looking to solve?

Hi,
Thanks for those great images.
Could you please publish the latest Beta?
https://static.tp-link.com/upload/beta/2023/202310/20231027/Omada_SDN_Controller_v5.13.10_Linux_x64.deb(Beta).zip

Thanks!

**Comment by Gruni22** [comment]
Link seems not to work. You may find it here

[https://community.tp-link.com/en/business/forum/topic/628384](https://community.tp-link.com/en/business/forum/topic/628384)

**Comment by mbentley** [comment]
Their links tend to have a user-agent or origin checker against them.  I'll need to use the `https://static.tp-link.com/upload/beta/2023/202310/20231027/Omada_SDN_Controller_v5.13.10_Linux_x64.tar.gz(Beta).gz` instead of the deb.  And of course, they have inconsistent packaging of their binaries.  The last beta version was a .zip file and now this one is gzipped so I will have to change the install.sh again.

**Comment by Gruni22** [comment]
Thank you!

**Comment by mbentley** [comment]
Beta 5.13.10 is available now in case you didn't see #359 and #362
