### ISSUE TITLE
capitive portal picture upload

### ISSUE THREAD

**Issue by jfitc004** [mbentley/docker-omada-controller#89]
I may be in over my head...

I am running the docker container omada version 4.2 in proxmox and on Site Settings>Authetication>Portal I keep getting an error when trying to upload a custom background picture for captive portal. When I try to apply a 770 kB jpg or 200 kB jpeg, I get an error message "Failed to upload. Select a picture no more than 1MB."

What makes things more interesting to me, is that the info next to the background picture choose icon says "choose a picture no more than 2MB"

This is my first docker container on proxmox and I would consider myself a novice at both.

I am not sure where I went wrong as there seems to be nothing in the logs.

**Comment by mbentley** [comment]
I don't know why it would be complaining about 1MB.  You aren't running any sort of reverse proxy in front that could be reducing the limit are you?  What is the exact version you're running?  I am running `4.2.11` which should be the latest and I can't reproduce this.

![omada](https://user-images.githubusercontent.com/414445/110037936-1a0c6980-7d0d-11eb-851a-a90a4d167947.gif)

If you're not running the latest, I would try to update to the latest image otherwise, you will need to file an issue upstream to the TP-Link forums as I do not have access to the source code to make changes: https://community.tp-link.com/en/business/forum/582
